image: docker:19.03.12

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - apk add curl
    - curl -sS --show-error --fail --data tag=${CI_COMMIT_TAG} "https://__token__:${DEPLOY_TOKEN}@gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/composer"
